apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: score
  name: score
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: score
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: score
    spec:
      containers:
        - image: fra.ocir.io/fruktknlrefu/oci_multiplayer/score:0.0.1
          name: score
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: score-properties
      imagePullSecrets:
        - name: ocir-secret
